_gremlin_insert_vertices = [
"g.addV('organization').property('id', 'org1').property('name', 'Hotel du la Poste').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org4').property('name', 'Group Hospital').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org6').property('name', 'Grand Hotel').property('about', 'It was located in Champagnole.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org8').property('name', 'Hotel Des Messageries').property('about', 'It was located in Salins.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org12').property('name', 'No. 2 Con hospital').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org14').property('name', 'French Red Cross').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org15').property('name', 'Hotel De Europe').property('about', 'It was located in Besancon.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org18').property('name', 'Hotel Moderne').property('about', 'There is a Hotel Moderne in both Paris and Dijon.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org19').property('name', 'Canadian Army Service Corps (CASC)').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org20').property('name', 'Truro News').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org21').property('name', '37 company').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org22').property('name', '85th Battalion').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org23').property('name', 'Russian soldiers').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org24').property('name', 'Hotel de Paris').property('about', 'It was located in Gray, France.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org25').property('name', 'Cantine Anglaise').property('about', 'The &quot;Cantine is run by the British branch of the French Red Cross&quot;. Is it in Gray France.').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org26').property('name', 'French equipment depot, Gray').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org27').property('name', 'No. 5 district').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org28').property('name', 'Seven Spades').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org29').property('name', 'Y.M.C.A.').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org31').property('name', '1st Bapt. Church Truro').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org32').property('name', 'Hotel Lyon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org33').property('name', '38 Company').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('organization').property('id', 'org34').property('name', '21 Company').property('about', '').property('partitionKey', 'partitionKey')"
]
