_gremlin_insert_vertices = [
"g.addV('location').property('id', 'loc1').property('name', 'Paris').property('about', '').property('latitude', '48.85341').property('longitude', '2.3488').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc8').property('name', 'Switzerland').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc9').property('name', 'Canada').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc11').property('name', 'Camp').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc12').property('name', 'London').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc15').property('name', 'Lajoux').property('about', 'The location of the camp for No 2 Construction.').property('latitude', '46.37437').property('longitude', '5.97329').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc16').property('name', 'England').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc18').property('name', 'S.A.').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc19').property('name', 'Bologne').property('about', 'I believe this location is Boulogne-sur-Mer since it is on the coast.').property('latitude', '50.72571').property('longitude', '1.61392').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc24').property('name', 'Nova Scotia').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc26').property('name', 'France').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc27').property('name', 'Jura').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc28').property('name', 'Ottawa').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc29').property('name', 'Marnay').property('about', '').property('latitude', '47.29088').property('longitude', '5.77277').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc30').property('name', 'Mouchard').property('about', '').property('latitude', '46.97259').property('longitude', '5.79626').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc31').property('name', 'Pontarlier').property('about', '').property('latitude', '46.90347').property('longitude', '6.35542').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc32').property('name', 'Salins').property('about', '').property('latitude', '46.94663').property('longitude', '5.87763').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc33').property('name', 'Morey').property('about', '').property('latitude', '46.800251').property('longitude', '4.600063').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc34').property('name', 'Champagnole').property('about', '').property('latitude', '46.74452').property('longitude', '5.91354').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc35').property('name', 'Arbois').property('about', '').property('latitude', '46.90311').property('longitude', '5.77454').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc36').property('name', 'Dole').property('about', '').property('latitude', '47.09225').property('longitude', '5.48966').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc37').property('name', 'Vosges').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc38').property('name', 'Andelot').property('about', '').property('latitude', '46.85258').property('longitude', '5.93368').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc39').property('name', 'Glacier Hill').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc40').property('name', 'Gray').property('about', 'Cantine Anglaise and Hotel de Paris are in Gray. Miss Wilford and Mrs. Anderson live here.').property('latitude', '47.44575').property('longitude', '5.59215').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc41').property('name', 'Besan&ccedil;on').property('about', '').property('latitude', '47.24878').property('longitude', '6.01815').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc42').property('name', 'Auxonne').property('about', '').property('latitude', '47.19255').property('longitude', '5.38726').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc43').property('name', 'Dijon').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc44').property('name', 'Alen&ccedil;on').property('about', '').property('latitude', '48.43476').property('longitude', '0.09311').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc45').property('name', 'Gare de Juvisy').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc46').property('name', 'Surdon').property('about', 'Railway station.').property('latitude', '48.66491').property('longitude', '0.13413').property('partitionKey', 'partitionKey')",
"g.addV('location').property('id', 'loc47').property('name', 'Versailles').property('about', '').property('latitude', '0.0').property('longitude', '0.0').property('partitionKey', 'partitionKey')"
]
