_gremlin_insert_vertices = [
"g.addV('person').property('id', 'per0').property('name', 'Capt. William White').property('name_last', 'White').property('about', 'No. 2 Construction chaplin').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per1').property('name', 'Mlles Thomas').property('name_last', 'Thomas').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per2').property('name', 'Mlles Dole').property('name_last', 'Dole').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per3').property('name', 'Mrs. White').property('name_last', 'White').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per4').property('name', 'Mrs. Fred Borden').property('name_last', 'Borden').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per5').property('name', 'Miss Jackson').property('name_last', 'Jackson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per6').property('name', 'Mrs. Frank Paris').property('name_last', 'Paris').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per8').property('name', 'Col. Johnson').property('name_last', 'Johnson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per9').property('name', 'Bro. Milton').property('name_last', 'Milton').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per10').property('name', 'Mme Levy').property('name_last', 'Levy').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per11').property('name', 'Pte Roach').property('name_last', 'Roach').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per12').property('name', 'Sister Campbell').property('name_last', 'Campbell').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per13').property('name', 'Syd Jones').property('name_last', 'Jones').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per15').property('name', 'Col. White').property('name_last', 'White').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per17').property('name', 'Joanne Dubied').property('name_last', 'Dubied').property('about', 'Joanne Dubied lives in Switzerland.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per18').property('name', 'Miss Walsh').property('name_last', 'Walsh').property('about', 'Miss Walsh lives in Switzerland.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per19').property('name', 'Frank Stanfield').property('name_last', 'Stanfield').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per21').property('name', 'Capt. Murray').property('name_last', 'Murray').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per22').property('name', 'Pte. Brent').property('name_last', 'Brent').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per23').property('name', 'Fred Dixon').property('name_last', 'Dixon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per24').property('name', 'Mary Clyke').property('name_last', 'Clyke').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per25').property('name', 'Mr. David-Mauvas').property('name_last', 'David-Mauvas').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per26').property('name', 'Miss Vera Ribbins').property('name_last', 'Ribbins').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per27').property('name', 'Lord Lovett').property('name_last', 'Lovett').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per28').property('name', 'Mrs. Bryant').property('name_last', 'Bryant').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per30').property('name', 'Sadie Lopez').property('name_last', 'Lopez').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per31').property('name', 'Rev. A. W. Thompson').property('name_last', 'Thompson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per32').property('name', 'Mrs. Alice White').property('name_last', 'White').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per33').property('name', 'Mrs. Henry Paris').property('name_last', 'Paris').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per34').property('name', 'Rev Thomas').property('name_last', 'Thomas').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per37').property('name', 'Ethel Williams').property('name_last', 'Williams').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per38').property('name', 'Lieut. Evans').property('name_last', 'Evans').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per39').property('name', 'Mrs. Talbot').property('name_last', 'Talbot').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per40').property('name', 'Sister Sarah.').property('name_last', 'Sarah').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per41').property('name', 'Hayes').property('name_last', 'Hayes').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per42').property('name', 'Leon Grybon').property('name_last', 'Grybon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per43').property('name', 'Mr. Hayes').property('name_last', 'Hayes').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per46').property('name', 'Mlle Rochaix').property('name_last', 'Rochaix').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per48').property('name', 'Gabrielle').property('name_last', 'Gabrielle').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per49').property('name', 'Marie').property('name_last', 'Marie').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per51').property('name', 'Mme Mayer').property('name_last', 'Mayer').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per52').property('name', 'Mlle Videlier').property('name_last', 'Vidlelier').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per56').property('name', 'Pte Roachford').property('name_last', 'Roachford').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per57').property('name', 'Bradshaw').property('name_last', 'Bradshow').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per60').property('name', 'Pte. Boone').property('name_last', 'Boone').property('about', 'Pte Boone was sick and died in hospital Dec. 1, 1917.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per62').property('name', 'Sarah').property('name_last', 'Sarah').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per63').property('name', 'J.H. Desmond').property('name_last', 'Desmond').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per64').property('name', 'Mrs. Anderson').property('name_last', 'Anderson').property('about', 'She lives in gray France and knows Miss Wilford.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per67').property('name', 'Col. McGreer').property('name_last', 'McGreer').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per68').property('name', 'Rev. Hartley').property('name_last', 'Hartley').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per69').property('name', 'Charley').property('name_last', 'Charley').property('about', 'Lives near Mrs. Henry Paris.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per70').property('name', 'Capt. Anderson').property('name_last', 'Anderson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per71').property('name', 'Henri Guyon').property('name_last', 'Guyon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per73').property('name', 'Mrs. McDougal').property('name_last', 'McDougal').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per74').property('name', 'Mrs. Wilson').property('name_last', 'Wilson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per75').property('name', 'Misses McCullough').property('name_last', 'McCullough').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per77').property('name', 'Mrs. Oscar Clyke').property('name_last', 'Clyke').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per80').property('name', 'Capt. Livingston').property('name_last', 'Livingston').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per81').property('name', 'Pte. Miller').property('name_last', 'Miller').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per83').property('name', 'Mrs. Izie White').property('name_last', 'White').property('about', 'Mrs. Izie White is married to Capt. William White.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per84').property('name', 'Mme Parrod').property('name_last', 'Parrod').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per85').property('name', 'Prof. Lapalus').property('name_last', 'Lapalus').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per86').property('name', 'Mme De Geger').property('name_last', 'De Geger').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per87').property('name', 'Mlle Jennie Leben').property('name_last', 'Leben').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per88').property('name', 'Dr. King').property('name_last', 'King').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per89').property('name', 'Rev. Logan').property('name_last', 'Logan').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per90').property('name', 'Mlle Wilford').property('name_last', 'Wilford').property('about', 'She lives in Gray, France and knows Mrs. Anderson.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per91').property('name', 'Bessie Paris').property('name_last', 'Paris').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per92').property('name', 'Lieut. Stewart').property('name_last', 'Stewart').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per93').property('name', 'Lieut. Colter').property('name_last', 'Colter').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per94').property('name', 'Mme Michault').property('name_last', 'Michault').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per95').property('name', 'Romney').property('name_last', 'Romney').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per96').property('name', 'Marie Gideon').property('name_last', 'Gideon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per97').property('name', 'Hayel').property('name_last', 'Hayel').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per99').property('name', 'Sgt. Stoute').property('name_last', 'Stoute').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per100').property('name', 'Miss Ford').property('name_last', 'Ford').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per101').property('name', 'Helena White').property('name_last', 'White').property('about', 'Helena is William and Izie White&apos;s daughter.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per102').property('name', 'Portia White').property('name_last', 'White').property('about', 'Portia White is the daughter of William White.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per103').property('name', 'Major Sutherland').property('name_last', 'Sutherland').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per104').property('name', 'Miss Bontoft').property('name_last', 'Bontoft').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per105').property('name', 'Senior Chaplain').property('name_last', 'Chaplain').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per106').property('name', 'Major MacDonald').property('name_last', 'MacDonald').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per107').property('name', 'Jen').property('name_last', 'Jen').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per108').property('name', 'Pte. Johnson').property('name_last', 'Johnson').property('about', 'He was batman for Capt. White.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per109').property('name', 'Mrs. Mentis').property('name_last', 'Mentis').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per110').property('name', 'Rev. States').property('name_last', 'States').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per111').property('name', 'Capt. Morrison').property('name_last', 'Morrison').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per112').property('name', 'Capt. Stark').property('name_last', 'Stark').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per113').property('name', 'Lieut. Purdy').property('name_last', 'Purdy').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per114').property('name', 'E. Boudot').property('name_last', 'Boudot').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per115').property('name', 'Madelein').property('name_last', 'Madelein').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per116').property('name', 'Ambassador of Brazil').property('name_last', 'Ambassador of Brazil').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per118').property('name', 'Sgt. Sealy').property('name_last', 'Sealy').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per120').property('name', 'Mlle Grandin').property('name_last', 'Grandin').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per121').property('name', 'Mlle Lapalus').property('name_last', 'Lapalus').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per122').property('name', 'Mrs. Fred Dixon').property('name_last', 'Dixon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per123').property('name', 'Raymonde').property('name_last', 'Raymonde').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per124').property('name', 'Mrs. Hattie Borden').property('name_last', 'Borden').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per125').property('name', 'Mrs. Carty').property('name_last', 'Carty').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per126').property('name', 'Lieut. Hood').property('name_last', 'Hood').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per127').property('name', 'Mme Menfoo').property('name_last', 'Menfoo').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per129').property('name', 'Major Legere').property('name_last', 'Legere').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per130').property('name', 'Mlle De Byars').property('name_last', 'De Byars').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per131').property('name', 'Mme Chauvin').property('name_last', 'Chauvin').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per132').property('name', 'Lieut. McLean').property('name_last', 'McLean').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per133').property('name', 'Mr. Thrope').property('name_last', 'Thrope').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per134').property('name', 'Mlle Deniset').property('name_last', 'Deniset').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per135').property('name', 'Mme Lea Chapuzot').property('name_last', 'Chapuzot').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per136').property('name', 'Nettie White').property('name_last', 'White').property('about', 'Nettie mentioned in the diary is likely William White&apos;s daughter.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per137').property('name', 'Billie (William) White').property('name_last', 'White').property('about', 'Billie mentioned in the diary is likely William White&apos;s son.').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per138').property('name', 'Mrs. Binga').property('name_last', 'Binga').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per139').property('name', 'Commandant, French equipment depot, Gray.').property('name_last', 'Commandant').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per140').property('name', 'Pte. Rochaix').property('name_last', 'Rochaix').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per141').property('name', 'Cpl. Binga').property('name_last', 'Binga').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per143').property('name', 'Capt. Pocunier').property('name_last', 'Pocunier').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per144').property('name', 'Baronne du Bourg').property('name_last', 'Bourg').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per145').property('name', 'Rev. Pusyear').property('name_last', 'Pusyear').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per146').property('name', 'F. B. McCurdy').property('name_last', 'McCurdy').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per147').property('name', 'Nursing Sisters').property('name_last', 'Nursing sisters').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per148').property('name', 'Agnes').property('name_last', 'Agnes').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per149').property('name', 'Major Strong').property('name_last', 'Strong').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per150').property('name', 'Col. Wilson').property('name_last', 'Wilson').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per151').property('name', 'Capt. McDougal').property('name_last', 'McDougal').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per153').property('name', 'Flight Lieut. P. Tostain').property('name_last', 'Tostain').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per154').property('name', 'Dr. Ortion').property('name_last', 'Ortion').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per155').property('name', 'Mr. Turner').property('name_last', 'Turner').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per156').property('name', 'Mrs. Sutherland').property('name_last', 'Sutherland').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per157').property('name', 'Mrs. Straith').property('name_last', 'Straith').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per158').property('name', 'Major Long').property('name_last', 'Long').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per159').property('name', 'Capt. Logan').property('name_last', 'Logan').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per160').property('name', 'Capt. Gordon').property('name_last', 'Gordon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per161').property('name', 'Capt. Stubbs').property('name_last', 'Stubbs').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per162').property('name', 'Lieut. Breckon').property('name_last', 'Breckon').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per163').property('name', 'Lieut. Lockman').property('name_last', 'Lockman').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per164').property('name', 'Capt. Grant').property('name_last', 'Grant').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per165').property('name', 'Mme Thomas').property('name_last', 'Thomas').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per166').property('name', 'Major Merrett').property('name_last', 'Merrett').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per167').property('name', 'Mme Monin').property('name_last', 'Monin').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per168').property('name', 'Capt. Latimore').property('name_last', 'Latimore').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per169').property('name', 'Major Carew').property('name_last', 'Carew').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per170').property('name', 'Mme Planche').property('name_last', 'Planche').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per171').property('name', 'Miss Blackadar').property('name_last', 'Blackadar').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per172').property('name', 'Miss McCully').property('name_last', 'McCully').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per173').property('name', 'Miss McDorman').property('name_last', 'McDorman').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per174').property('name', 'Sgt.Q.M. Peacock').property('name_last', 'Peacock').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per175').property('name', 'Mrs. Tucker').property('name_last', 'Tucker').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per176').property('name', 'Mrs. Parsons').property('name_last', 'Parsons').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per177').property('name', 'Emily').property('name_last', 'Emily').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per178').property('name', 'Capt. Bourassa').property('name_last', 'Bourassa').property('about', '').property('partitionKey', 'partitionKey')",
"g.addV('person').property('id', 'per179').property('name', 'Mme Johnson').property('name_last', 'Johnson').property('about', '').property('partitionKey', 'partitionKey')"
]
